#M2#A77 - ES6 - Promises
A Promise é um construtor que é utilizado para tratar chamadas asyncronas além de poder pegar funcões que possuem callback e fazer com que retorne promises para realizarem tarefas específicas mantendo assim o código mais legível.

Ela possui dois argumentos que são funcões.
- Primeiro é o que resolve quando existe um sucesso
- Segundo é quando a Promisse não obtem o valor esperado

Aqui declaramos nossa `Promisse` com um único resultado de sucesso. Primeiro instanciamos nossa promise e depois chamamos o método junto de `then()` passando uma funcão que mostre o nosso resultado.

```
const promise = new Promise((resolve, reject) => {
  resolve('resolvida')
})

promise.then((result) => console.log(result))
```

### Pegando as reijeicões.
Precisamos utilizar o método `catch` para conseguir capturar o erro na `Promise`.

```
const promise = new Promise((resolve, reject) => {
  reject('rejeitada')
})

promise
  .then((result) => console.log(result))
  .catch((error) => console.log('ERROR: ', error))
```


### Exemplo

#### Sem promise
Vamos criar uma funcão que leia arquivos.

Estamos utilizando o método `fs` do node que dá poder para lermos os arquivos e o método `path` para termos acesso aos caminhos dos arquivos.
```
const fs = require('fs')
const path = require('path')
```

Utilizamos a funcão `readFile` que possui 3 parâmetros:
- a:  o caminho do arquivo que deve ser completo
- b:  é o tipo de codificação do arquivo
- c: é uma função de callback que retorna o err como primeiro argumento e o segundo o resultado

```
fs.readFile(a, b, (err, result) => { })
```
Criando funcão
```
fs.readFile(path.join(__dirname, '..', 'package.json'), 'utf8', (err, result) => {
  if (err) return console.log('ERROR:', err)
  console.log(result)
})
```

#### Com promise

Vamos criar a função `readFile` e fazer com que ela retorne uma promise

Criamos a função readFile e passamos os argumentos necessários e retornamos uma Promise.

```
const readFile = (filePath, charset) => new Promise((resolve, reject) => {

})
```

Colocamos agora a funcão dentro da nossa `Promise` passando os argumentos, retornando os métodos `reject` para erro e  `resolve` para solucão.

```
const readFile = (filePath, charset) => new Promise((resolve, reject) => {
  fs.readFile(filePath, charset, (err, result) => {
    if (err) return reject(err)
    resolve(result)
  })
})
```

### Podemos ter vários `then`
Quando utilizamos `then` encadeados ele passa o retorno do anterior para o próximo sendo assim podendo ser manipulado.

Exemplo
```
readFile(path.join(__dirname, '..', 'package.json'), 'utf8')
  .then((result) =>  JSON.parse(result).dependencies) // como teve o sucesso
  .then((myDependencies) => console.log(myDependencies)) // abaixo temos o retorno do primeiro then aqui
  .catch((error) =>  console.log('ERROR: ', error))
```

